# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "RECOMB-P&E Conference"
email: "recomb-privacy-equity@googlegroups.com"
description: "RECOMB Satellite Conference on Biomedical Privacy and Equity"
baseurl: ""
url: "https://recomb-privacy-equity.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: "recomb-privacy-equity.github.io"
siteVerification: ""

# Organizer Info
organizerName: "RECOMB-P&E"
organizerAlternateName: "RECOMB-P&E"
organizerDescription: "A research community tackling privacy and equity challenges in biomedical research"
organizerEmail: "recomb-privacy-equity@googlegroups.com"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "https://github.com/RECOMB-Privacy-Equity"

# Head
metaKeywords: "recomb, privacy, equity"
# twitterAccount: "@recombseq"
# socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Navigation
navigationLinks:
 - {permalink: "/2025/", text: "Home"}
 - {permalink: "/2025/papers/", text: "Call for Papers"}
 - {permalink: "/2025/team/", text: "Committees"}
 - {permalink: "/2025/speakers/", text: "Keynote Speakers"}
 - {permalink: "/2025/program/", text: "Program"}
# - {permalink: "/history/", text: "History of RECOMB SEQ"}
bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Submit a paper"}
rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Submit a paper"}

# Hero Block
heroImage: "dna-dark.jpg"
heroTitle: "RECOMB-P&E 2025"
heroSubTitle: "The 2nd RECOMB Satellite Conference on Biomedical Privacy and Equity"
eventDate: "April 25, 2025"
eventLocation: "Seoul, South Korea"
#typeoutTextValues: '"2023"'
#typeoutFallback: "2023"
heroButtons:
 #- {link: "https://bit.ly/dfua-c4p", text: "Submit a paper"}
 #- {permalink: "/#tickets", text: "Attend RECOMB SEQ 2023"}

# About Block
aboutTitle: "About RECOMB P&E"
# aboutBlock:
# - {title: "RECOMB-SEQ", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
# - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
# - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of pure Google technologies"}
 - {count: "20", specialCharacter: "+", info: "speakers", detail: "from country and beyond"}
 - {count: "3", specialCharacter: "", info: "parallel tracks", detail: "plus entertainment lounge"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "TBD"
eventLocationLink: "TBD"
eventStreetAddress: "TBD"
eventAddressLocality: ""
eventAddressLocalityRegion: "Seoul"
eventPostalCode: ""
eventAddressCountry: "South Korea"
eventStartTime: "2025-04-24T08:00"
eventDoorTime: "09:00"
eventEndTime: "2025-04-25T18:00"
eventPlaceCoordinates: "37.5617613,126.9353254"
mapCenterCoordinates: "37.5617613,126.9353254"
mapMobileCenterCoordinates: "37.5617613,126.9353254"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "TBD"
venueFeatures: [""]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "RECOMBPrivacyEquity"
#twitterFeed: " https://twitter.com/recombseq"



# Footer
socialLinks:
 #- {permalink: "/feed.xml", icon: "rss"}
# - {link: "https://twitter.com/recombseq", icon: "twitter"}
# - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
# - {link: "https://www.youtube.com/@recomb-seq", icon: "youtube"}
footerBlocks:
  # -
  # title: "Links"
  # links:
  # - {link: "https://recomb2022.net", text: "RECOMB 2022"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:recomb-privacy-equity@googlegroups.com", text: "recomb-privacy-equity@googlegroups.com"}
 -
  title: "Policies"
  links:
   - {permalink: "/coi/", text: "Conflict-of-interest Policy"}
   # - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Collections
collections:
  paper-calls:
    output: true
# Speakers List Block
showSessions: true

# Team Block
#teamBlockTitle: "About us"
#aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

